/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    CartSidebar: typeof import('./components/CartSidebar.vue')['default']
    Checkout: typeof import('./components/Checkout.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    MenuBar: typeof import('./components/MenuBar.vue')['default']
    Pay: typeof import('./components/Pay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shop: typeof import('./components/Shop.vue')['default']
    ShopPlatzi: typeof import('./components/ShopPlatzi.vue')['default']
    Todo: typeof import('./components/Todo.vue')['default']
  }
}
